services:
#  app:
#    build:
#      context: ./app
#      target: runner
#    image: classwayx-app-prod
#    container_name: classwayx-app-prod-container
#    ports:
#      - "3000:3000"
#    restart: always
#    depends_on:
#      db-init:
#        condition: service_completed_successfully

  db-init:
    image: postgres:17.10-alpine3.24
    container_name: classwayx-db-init
    environment:
      LARK_BOT_USER: ${LARK_BOT_USER}
      LARK_BOT_USER_PASSWORD: ${LARK_BOT_USER_PASSWORD}
      LARK_BOT_DB_NAME: ${LARK_BOT_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGPASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db_init.sql:/app/db_init.sql
    command: >
      sh -c "
      psql
      --set ON_ERROR_STOP=1
      --set lark_bot_db=$$LARK_BOT_DB_NAME
      --set lark_bot_user=$$LARK_BOT_USER
      --set lark_bot_user_password=$$LARK_BOT_USER_PASSWORD
      -h postgres
      -U $$POSTGRES_USER
      -d $$POSTGRES_DB
      -f /app/db_init.sql"

  lark-bot-db-migration:
    build:
      context: ./lark-bot
      target: dependencies
    image: lark-bot-db-migration
    container_name: lark-bot-db-migration-container
    env_file:
      - ./lark-bot/.env
    command: npx prisma migrate deploy
    restart: no
    volumes:
      - ./lark-bot:/app
      - /app/node_modules
    depends_on:
      db-init:
        condition: service_completed_successfully

  lark-bot:
    build:
      context: ./lark-bot
      target: runner
    image: classwayx-lark-bot-prod
    container_name: classwayx-lark-bot-prod-container
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      lark-bot-db-migration:
        condition: service_completed_successfully

  postgres:
    image: postgres:17.10-alpine3.24
    container_name: classwayx-postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - classwayx-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s

volumes:
  classwayx-pgdata: