services:
  app:
    build:
      context: ./app
      target: runner
    image: classwayx-app-prod
    container_name: classwayx-app-prod-container
    ports:
      - "3000:3000"
    restart: always

  postgres:
    image: postgres:17.10-alpine3.24
    container_name: classwayx-postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - classwayx-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  classwayx-pgdata: